site_name: Arista AVD Fabric Documentation.
site_author: Arista Ansible Team
site_description: Arista Cloudvision collection's documentation
docs_dir: documentation/
# site_favicon: docs/_media/favicon.ico
theme:
  name: material
  features:
    - instant
#   font:
#     text: Ubuntu
#     code: Ubuntu Mono
extra_css:
  - stylesheet.css
copyright: Copyright &copy; 2019 - 2020 Arista Networks
repo_name: AVD Collection
repo_url: https://github.com/aristanetworks/ansible-avd
use_directory_urls: true
nav:
  - Fabric overview:
      - IPAM: DC1_FABRIC/DC1_FABRIC.md
  - Devices documentation:
      - DC1-SPINE1: devices/DC1-SPINE1.md
      - DC1-SPINE2: devices/DC1-SPINE2.md
      - DC1-LEAF1A: devices/DC1-LEAF1A.md
      - DC1-LEAF1B: devices/DC1-LEAF1B.md
      - DC1-LEAF2A: devices/DC1-LEAF2A.md
      - DC1-LEAF2B: devices/DC1-LEAF2B.md
      - DC1-L2LEAF1A: devices/DC1-L2LEAF1A.md
      - DC1-L2LEAF2A: devices/DC1-L2LEAF2A.md
